name: build_release

on:
  create:
    tags:
      - 'v*' # 触发条件为以 'v' 开头的 tag

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-os: [windows, linux, darwin]  # 可以根据需要添加或修改
        go-arch: [amd64]         # 可以根据需要添加或修改
        include:
          - go-os: linux
            go-arch: arm64
          - go-os: windows
            go-arch: arm64
          - go-os: darwin
            go-arch: arm64
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.21

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=${{ matrix.go-os }} GOARCH=${{ matrix.go-arch }} go build -a -tags netgo -ldflags '-w' -o ${{ secrets.FILE_NAME }}-${{ matrix.go-os }}-${{ matrix.go-arch }} ./
    - name: Rename Windows Binary
      if: matrix.go-os == 'windows'
      run: |
        mv ${{ secrets.FILE_NAME }}-${{ matrix.go-os }}-${{ matrix.go-arch }} ${{ secrets.FILE_NAME }}-${{ matrix.go-os }}-${{ matrix.go-arch }}.exe
    - name: Archive
      run: tar -czvf ${{ secrets.FILE_NAME }}-${{ matrix.go-os }}-${{ matrix.go-arch }}.tar.gz ${{ secrets.FILE_NAME }}-${{ matrix.go-os }}-${{ matrix.go-arch }}*

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.CUSTOM_TOKEN }}
        file: ./${{ secrets.FILE_NAME }}-${{ matrix.go-os }}-${{ matrix.go-arch }}.tar.gz
        tag: ${{ github.ref }}
        file_glob: true
